export const IDLE = 'IDLE';
export const CHECKING_FOR_UPDATE = 'CHECKING_FOR_UPDATE';
export const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE';
export const UPDATE_NOT_AVAILABLE = 'UPDATE_NOT_AVAILABLE';
export const UPDATE_DOWNLOADING = 'UPDATE_DOWNLOADING';
export const UPDATE_DOWNLOADED = 'UPDATE_DOWNLOADED';
export const UPDATE_ERROR = 'UPDATE_ERROR';
